+incdir+$UVM_HOME/src
$UVM_HOME/src/uvm_pkg.sv
+incdir+$WORK_HOME/jay_driver
+incdir+$WORK_HOME/jay_dut
$WORK_HOME/jay_dut/snvs_lp_zmk_ff.v
$WORK_HOME/jay_dut/snvs_lp_zmk.v
+incdir+$WORK_HOME/jay_trans
+incdir+$WORK_HOME/jay_env
+incdir+$WORK_HOME/jay_monitor
+incdir+$WORK_HOME/jay_reference
+incdir+$WORK_HOME/jay_agent
+incdir+$WORK_HOME/jay_scoreboard
$WORK_HOME/jay_if/zmk_if.sv
$WORK_HOME/jay_top/top_tb.sv
