#ifndef __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned RP;
typedef unsigned RO;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprNode;
typedef union {
    double I463;
    unsigned long long I446;
    unsigned  I464[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
struct eblk {
    struct eblk * I451;
    E_fn  I452;
    struct iptmpl * I453;
    unsigned I461;
    struct eblk * I462;
};
typedef struct {
    RP  I451;
    RP  I452;
    RP  I453;
    unsigned I461;
    RP  I462;
} RmaEblk;
typedef union {
    double I463;
    unsigned long long I446;
    unsigned  I464[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RmaEblk  I450;
    RP  I475;
    RP  I476;
    U  I477;
    US  I478 :1;
    US  I479 :4;
    US  newval :2;
    US  I481 :2;
    US  I161 :2;
};
typedef struct RmaMPSched RmaMps;
struct RmaMPSched {
    scalar  I483;
    scalar  I484;
    US  I485 :9;
    US  fHsim :1;
    US  I161 :6;
    RP  I487;
    RmaEblk  I488;
    RP  I489;
    RP   I490[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    scalar  I483;
    scalar  I484;
    US  I485 :10;
    US  I161 :6;
    RP  I487;
    RmaEblk  I488;
    scalar  I492;
    scalar  I493;
    scalar  I494;
    scalar  I495;
    U  I496;
    RmaClockStruct  I497;
    RmaClockStruct  I498;
    U  state;
    U  I500;
    RP  I453;
    RP  I501;
    RP  I502;
    RP   I490[1];
};
typedef struct {
    RmaEblk  I450;
    RP  I503;
    scalar  I504;
    scalar  I492;
    scalar  I505;
} RmaTransEventHdr;
typedef struct red_t {
    U  I506;
    U  I507;
    U  I508;
} RED;
typedef struct predd {
    PD_e  I161;
    RED   I509[1];
} PREDD;
typedef unsigned long long ULL;
typedef struct {
    RP  I510;
    RP  I501;
    RP  I453;
    RP  I502;
    RmaEblk  I450;
    RmaEblk  I511;
    RP  I512;
    scalar  I504;
    scalar  I492;
    char state;
    uscope_t  I513;
    U  I514;
    RP  I515;
    scalar  I493;
    scalar  I494;
    scalar  I495;
    RmaClockStruct  I497;
    RmaClockStruct  I498;
    RP  I489;
} RmaPulse;
typedef U  FlatNodeNum;
typedef U  InstNum;
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2
} QIRDModuleType;
typedef struct {
    U  I516 :1;
    U  I517 :1;
    U  I518 :1;
    U  I519 :1;
    U  I520 :1;
    U  I521 :1;
    U  I522 :1;
    U  I523 :1;
    U  I524 :1;
    U  I525 :1;
    U  I526 :1;
    U  I527 :1;
    U  I528 :1;
    U  I529 :1;
    U  I530 :1;
    U  I531 :1;
    U  I532 :1;
    U  I533 :1;
    U  I534 :1;
    U  I535 :1;
    QIRDModuleType  I536 :2;
    U  I537 :1;
    U  I538 :1;
    U  I539 :1;
    U  I540 :1;
    U  I541 :1;
    U  I542 :1;
    U  I543 :1;
    U  I544 :1;
    U  I545 :1;
    U  I546 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    U  I12;
    U  I13;
    struct vcd_rt * I14;
    U  I16;
    struct _vcdOffset_rt * I17;
    U  I19;
    U  I20;
    U  * I21;
    U  * I22;
    void * I23;
    U  I24;
    int I25;
    UP  I26;
    U  I27;
    U  I28;
    U  I29;
    UP  I30;
    U  * I31;
    BitFlags  I32;
    U  I33;
    U  I34;
    U  I35;
    U  I36;
    U  I37;
    U  * I38;
    U  I39;
    U  * I40;
    U  I41;
    U  I42;
    U  I43;
    U  I44;
    U  I45;
    U  I46;
    U  I47;
    U  * I48;
    U  I49;
    U  I50;
    U  * I51;
    U  I52;
    U  * I53;
    U  I54;
    U  I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  I65;
    U  I66;
    U  * I67;
    char * I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    U  I75;
    U  I76;
    U  I77;
    UP  * I78;
    U  I79;
    U  I80;
    U  I81;
    U  I82;
    U  I83;
    U  I84;
    U  * I85;
    U  I86;
    U  I87;
    U  * I88;
    U  * I89;
    U  * I90;
    U  * I91;
    U  * I92;
    U  I93;
    U  I94;
    struct taskInfo * I95;
    U  I97;
    U  I98;
    int * I99;
    U  I100;
    U  I101;
    U  I102;
    U  I103;
    U  I104;
    struct qrefer * I105;
    U  * I107;
    unsigned * I108;
    void * I109;
    U  I110;
    U  I111;
    U  I112;
    U  I113;
    U  * I114;
    U  I115;
    U  * I116;
    U  I117;
    U  I118;
    U  I119;
    U  * I120;
    U  I121;
    U  * I122;
    U  I123;
    U  I124;
    U  * I125;
    U  I126;
    U  I127;
    U  * I128;
    U  * I129;
    U  * I130;
    U  I131;
    U  I132;
    U  I133;
    U  I134;
    U  I135;
    struct qrefee * I136;
    U  * I138;
    U  I139;
    struct qdefrefee * I140;
    U  * I142;
    int (* I143)(void);
    char * I144;
    U  I145;
    U  I146;
    void * I147;
    NumLibs_t  I148;
    char * I149;
    U  * I150;
    U  I151;
    U  I152;
    U  I153;
    U  I154;
    U  I155;
    U  * I156;
    U  * I157;
    int I158;
    struct clock_load * I159;
    int I174;
    struct clock_data * I175;
    int I191;
    struct clock_hiconn * I192;
    U  I196;
    int I197;
    U  I198;
    int I199;
    U  * I200;
    U  * I201;
    U  I202;
    void * I203;
    U  I204;
    U  I205;
    UP  * I206;
    void * I207;
    U  I208;
    UP  * I209;
    U  * I210;
    int (* I211)(void);
    U  * I212;
    UP  * I213;
    U  * I214;
    U  I215;
    U  I216;
    U  I217;
    UP  * I218;
    U  * I219;
    U  I220 :1;
    U  I221 :1;
    U  I222 :30;
    UP  * I223;
    UP  * I224;
    U  * I225;
    U  * I226;
    UP  * I227;
    UP  * I228;
    UP  * I229;
    U  * I230;
    UP  * I231;
    UP  * I232;
    U  I233;
    U  I234;
    U  I235;
    U  I236;
    U  I237;
    U  I238;
    U  I239;
    struct daidirInfo * I240;
    struct vcs_tftable * I242;
    U  I244;
    UP  (* I245)(void);
    UP  (* I246)(void);
    UP  (* I247)(void);
    UP  (* I248)(void);
    int * I249;
    int (* I250)(void);
    char * I251;
    UP  * I252;
    UP  * I253;
    int (* I254)(void);
    int * I255;
    U  * I256;
    void * I257;
    U  I258;
    U  I259;
    U  I260;
    U  I261;
    U  I262;
    U  I263;
    UP  * I264;
    U  * I265;
    U  * I266;
    U  I267 :15;
    U  I268 :14;
    U  I269 :1;
    U  I270 :1;
    U  I271 :1;
    U  I272 :3;
    U  I273 :1;
    U  I274 :28;
    struct scope * I275;
    U  I277;
    U  I278;
    U  * I279;
    U  * I280;
    U  * I281;
    U  I282;
    U  I283;
    U  I284;
    struct pcbt * I285;
    U  I294;
    U  I295;
    void * I296;
    int I297;
    U  I298;
    U  I299;
    U  I300;
    U  I301;
    U  I302;
    void * I303;
    UP  * I304;
    U  I305;
    U  I306;
    void * I307;
    U  I308;
    void * I309;
    U  I310;
    void * I311;
    U  I312;
    int (* I313)(void);
    int (* I314)(void);
    void * I315;
    void * I316;
    void * I317;
    U  I318;
    U  I319;
    char * I320;
    U  I321;
    U  * I322;
    U  I323;
    U  * I324;
    U  I325;
    U  I326;
    U  I327;
    U  I328;
    U  I329;
    U  I330;
    U  * I331;
    U  I332;
    U  I333;
    U  * I334;
    U  I335;
    U  * I336;
    char * I337;
    U  I338;
    U  I339;
    U  I340;
    U  I341;
    U  * I342;
    U  I343;
    U  I344;
    struct cosim_info * I345;
    U  I347;
    U  * I348;
    U  I349;
    U  I350;
    U  * I351;
    U  I352;
    U  * I353;
    U  I354;
    U  I355;
    U  * I356;
    U  I357;
    U  I358;
    U  I359;
    U  * I360;
    U  I361;
    U  I362;
    U  I363;
    U  I364;
    U  I365;
    U  I366;
    U  I367;
    U  I368;
    U  * I369;
    U  * I370;
    void (* I371)(void);
    U  * I372;
    UP  * I373;
    struct mhdl_outInfo * I374;
    UP  * I376;
    U  I377;
    UP  * I378;
    U  I379;
    void * I380;
    U  * I381;
    void * I382;
    U  I383;
    U  I384;
    void * I385;
    void * I386;
    U  * I387;
    U  * I388;
    U  * I389;
    U  * I390;
    void * I391;
    U  I392;
    void * I393;
    U  * I394;
    char * I395;
    int (* I396)(void);
    U  * I397;
    char * I398;
    char * I399;
    U  I400;
    U  * I401;
    struct regInitInfo * I402;
    UP  * I404;
    U  * I405;
    char * I406;
    U  I407;
    U  I408;
    U  I409;
    U  I410;
    U  I411;
    U  I412;
    U  I413;
    U  * I414;
    U  * I415;
    U  I416;
    U  I417;
    U  I418;
    UP  * I419;
    U  I420;
    UP  * I421;
    U  I422;
    U  I423;
    U  I424;
    U  * I425;
    U  * I426;
    UP  * I427;
    UP  * I428;
    void * I429;
    UP  I430;
    U  I431;
    U  I432;
    U  I433;
    U  I434;
    U  * I435;
    U  I436;
    U  * I437;
    U  I438;
    U  I439;
    U  * I440;
};
typedef struct pcbt {
    U  * I287;
    UP  I288;
    U  I289;
    U  I290;
    U  I291;
    U  I292;
    U  I293;
} PCBT;
struct iptmpl {
    QIRD  * I455;
    struct vcs_globals_t * I456;
    void * I458;
    UP  I459;
    UP  I460;
    struct iptmpl * I453[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I561[256];
    struct _hsimPeriodL * I547;
} HsimPeriodL;
typedef struct {
    U   I563[2];
    U  I564 :1;
    U  I565 :1;
    U  I566 :8;
    U  I567 :8;
    U  I568 :8;
    U  I569 :4;
    unsigned long long I570;
    unsigned long long I571;
    unsigned long long I572;
    unsigned long long I573;
    unsigned long long I574;
    U  I575;
    U  I576;
    U  I577;
    U  I578;
    HsimPeriodL  * I579;
    HsimPeriodL  * I580;
    U  I581;
} HsimSignalMonitor;
typedef struct {
    scalar  I582;
    U  I583;
    U  I584;
    U  I585;
    U  I586;
    U  I587;
    U  I588;
    U  I589;
    HsimSignalMonitor  * I590;
    long long I591;
    U  I592;
    FlatNodeNum  I593;
    InstNum  I594;
} HsimNodeRecord;
typedef struct {
    RP  I595;
    RP  I453;
} RmaIbfIp;
typedef struct {
    RP  I595;
    RP  I596;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I450;
    RP  I597;
    vec32  I598;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I450;
    RP  I597;
    vec32   I599[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I450;
    RP  I597;
    scalar   I600[1];
} RmaAnySchedECg;
typedef struct {
    RP  I601;
} RmaRootCbkCg;
typedef struct {
    U  I602;
} RmaRootVcdCg;
typedef struct {
    RP  I603;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I450;
    RP  I596;
    U   I444[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I509;
    RmaEblk  I450;
    RmaIbfPcode  I607;
} RmaGateDelay;
typedef struct {
    U  I5;
    union {
        RP  I740;
        RP  I846;
        RP  I852;
    } I475;
    RmaIbfPcode  I607;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I608;
    RmaIbfPcode  I607;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I607;
    RmaMps  I609;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I610;
    RmaIbfPcode  I607;
    RmaEblk  I488;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaMpsp  I611;
    RmaIbfPcode  I607;
} RmaMPPulseOptHybridDelay;
typedef struct {
    U  I5;
    U  I508;
    RmaTransEventHdr  I548;
    RP  I612;
    RmaIbfPcode  I607;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I508;
    RmaEblk  I450;
    RmaIbfPcode  I607;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I450;
    RmaIbfPcode  I607;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I613;
    U  I614;
    RmaTransEventHdr  I548;
    RP  I612;
    RmaIbfPcode  I607;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I613;
    U  I614;
    RmaEblk  I450;
    RmaIbfPcode  I607;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I509;
    RmaEblk  I450;
    RmaIbfPcode  I607;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I846;
        RP  I852;
    } I475;
    RmaIbfPcode  I607;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I509;
    RmaEblk  I450;
    RmaIbfPcode  I607;
} RmaPortDelay;
typedef struct TableAssign_ {
    struct TableAssign_ * I547;
    struct TableAssign_ * I503;
    U  I5;
    RP  ptable;
    RP  I617;
} TableAssign;
typedef struct TableAssignList_ {
    U  I5;
    TableAssign  * I503;
    struct TableAssignList_ * I618;
    TableAssign   arr[1];
} TableAssignList;
typedef struct {
    RP  I547;
    RP  I621;
    RP  I447;
    U  I622 :30;
    U  I623 :1;
    U  I624 :1;
} RmaTcCoreSimple;
typedef struct {
    RP  I547;
    RP  I621;
    RP  I447;
    U  I622 :30;
    U  I623 :1;
    U  I624 :1;
    RP  I625;
} RmaTcCoreConditional;
typedef struct {
    RP  I621;
    RP  I447;
    U  I622 :30;
    U  I623 :1;
    U  I624 :1;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I621;
    RP  I447;
    U  I622 :30;
    U  I623 :1;
    U  I624 :1;
    RP  I625;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I626;
    U  I627;
    scalar  I628;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I547;
    RP  I626;
    U  I627;
    scalar  I628;
} RmaConditionalTSLoad;
typedef struct {
    US  I629;
    scalar  val;
    RmaIbfPcode  I607;
} RmaScanSwitchData;
struct clock_load {
    U  I161 :5;
    U  I162 :12;
    U  I163 :1;
    U  I164 :2;
    U  I165 :1;
    U  I166 :1;
    U  I167 :1;
    U  I168 :9;
    U  I169;
    U  I170;
    void (* pfn)(void * I172, char val);
};
typedef struct clock_data {
    U  I177 :1;
    U  I178 :1;
    U  I179 :1;
    U  I180 :1;
    U  I161 :5;
    U  I162 :12;
    U  I181 :6;
    U  I182 :1;
    U  I164 :2;
    U  I165 :1;
    U  I168 :1;
    U  I183;
    U  I184;
    U  I185;
    U  I169;
    U  I186;
    U  I187;
    U  I188;
    U  I189;
    U  I190;
} HdbsClockData;
struct clock_hiconn {
    U  I194;
    U  I195;
    U  I169;
    U  I164;
};
typedef struct _RmaDaiCg {
    RP  I630;
    RP  I631;
    U  I632;
} RmaDaiCg;
struct futq {
    struct futq * I465;
    struct futq * I467;
    RmaEblk  * I468;
    RmaEblk  * I469;
    U  I461;
};
struct sched_table {
    struct futq * I470;
    struct futq I471;
    struct hash_bucket * I472;
};
struct dummyq_struct {
    clock_struct  I633;
    EBLK  * I634;
    EBLK  * I635;
    struct futq * I636;
    struct futq * I637;
    struct sched_table * I638;
    struct millenium * I640;
    EBLK  * I642;
    EBLK  * I643;
    EBLK  * I644;
    EBLK  * I645;
    EBLK  * I646;
    EBLK  * I647;
    EBLK  * I648;
    EBLK  * I649;
    EBLK  * I650;
    EBLK  * I651;
    EBLK  * I652;
    EBLK  * I653;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   XcvtstrTR[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0lq(UB *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, UB *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv,	scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(U ts,RP* pdata, U fskew, U limit, U floaded);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, void*, U);
extern int memcmp(void*, void*, U);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);


#ifdef __cplusplus
extern "C" {
#endif
void  hsF_0_0_0_(UB  * I596, vec32  * I597, U  I715);
void  hsF_0_0_6_(UB  * I596, scalar  val, U  I707);
void  hsF_0_0_7_(UB  * I596, vec32  * val, U  I707, U  I724);
void  hsF_0_0_9_(UB  * I596, vec32  * I597);
void  hsF_0_1_0_(UB  * I596, scalar  val);
void  hsF_0_2_0_(UB  * I596, vec32  * I597, U  I715);
void  hsF_0_2_6_(UB  * I596, scalar  val, U  I707);
void  hsF_0_2_7_(UB  * I596, vec32  * val, U  I707, U  I724);
void  hsF_0_2_9_(UB  * I596, vec32  * I597);
void  hsC_0_3_0_(UB  * I596, scalar  val);
void  hsF_0_4_0_(UB  * I596, scalar  val);
void  hsF_0_5_0_(UB  * I596, scalar  val);
void  schedNewEvent(struct dummyq_struct * I659, EBLK  * I660, U  I508);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

